package com.example.hospitalapi.Exception;

import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

@ControllerAdvice // Tells Spring to check this class first whenever an exception is thrown in any controller
@Slf4j
public class GlobalExceptionHandler {
    // Handles cases where a requested resource does not exist.
    // Logs the original error and returns a standardized HTTP 404 response
    // so the client knows the requested entity could not be found.
    @ExceptionHandler(ResourceNotFoundException.class)
    public ResponseEntity<Map<String, Object>> handleResourceNotFoundException(ResourceNotFoundException ex) {
        log.error("Error: {}", ex.getMessage());
        return buildResponse(HttpStatus.NOT_FOUND, ex.getMessage());
    }

    // Handles business rule violations that prevent an operation from being completed.
    // Logs the business error and returns an HTTP 409 Conflict response
    // indicating that the request is valid but violates application rules.
    @ExceptionHandler(BusinessException.class)
    public ResponseEntity<Map<String, Object>> handleBusinessException(BusinessException ex) {
        log.error("Business Error: {}", ex.getMessage());
        return buildResponse(HttpStatus.CONFLICT, ex.getMessage());
    }

    // Handles requests containing invalid or inconsistent input data.
    // Logs the validation issue and returns an HTTP 400 Bad Request response
    // so the client can correct the submitted information.
    @ExceptionHandler(InvalidRequestException.class)
    public ResponseEntity<Map<String, Object>> handleInvalidRequestException(InvalidRequestException ex) {
        log.error("Petition not valid: {}", ex.getMessage());
        return buildResponse(HttpStatus.BAD_REQUEST, ex.getMessage());
    }

    // Collects all field validation errors generated by Spring's Bean Validation.
    // Builds a map where each field is associated with its validation message
    // and returns it in a standardized HTTP 400 response.
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<Map<String, Object>> handleValidationErrors(MethodArgumentNotValidException ex) {
        log.error("Validation Error: {}", ex.getMessage());
        Map<String, String> validationErrors = new HashMap<>();
        ex.getBindingResult().getFieldErrors()
                .forEach(error -> validationErrors.put(error.getField(),
                        error.getDefaultMessage() != null ? error.getDefaultMessage() : "Invalid value"));
        return buildResponse(HttpStatus.BAD_REQUEST, validationErrors);
    }

    // Handles any unexpected exception that was not processed by a more specific handler.
    // Logs the complete exception, including the stack trace, and returns
    // a generic HTTP 500 response without exposing internal application details.
    @ExceptionHandler(Exception.class)
    public ResponseEntity<Map<String, Object>> handleGeneralException(Exception ex) {
        log.error("Unexpected Error", ex);
        return buildResponse(HttpStatus.INTERNAL_SERVER_ERROR, "An internal error occurred, please contact support");
    }
    // Creates a consistent error response structure shared by all exception handlers.
    // Includes the timestamp, HTTP status code, reason phrase, and the corresponding
    // error message to ensure every error response follows the same format.
    public ResponseEntity<Map<String, Object>> buildResponse(HttpStatus status, Object message) {
        Map<String, Object> body = new HashMap<>();
        body.put("timestamp", LocalDateTime.now());
        body.put("status", status.value());
        body.put("error", status.getReasonPhrase());
        body.put("message", message);
        return ResponseEntity.status(status).body(body);
    }
}






/*package com.example.hospitalapi.Exception;

import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

@ControllerAdvice
@Slf4j
public class GlobalExceptionHandler  {

    @ExceptionHandler(ResourceNotFoundException.class)
    public ResponseEntity<Map<String,Object>>handleResourceNotFoundException(ResourceNotFoundException ex){
        log.error("Error  : {}", ex.getMessage());
        return buildResponse(HttpStatus.NOT_FOUND, ex.getMessage());


    }@ExceptionHandler(BusinessException.class)
    public ResponseEntity<Map<String,Object>>handleBusinessException(BusinessException ex){
        log.error("Business Error : {}", ex.getMessage());
        return buildResponse(HttpStatus.CONFLICT, ex.getMessage());

    }


    @ExceptionHandler(InvalidRequestException.class)
    public ResponseEntity<Map<String,Object>>handleInvalidRequestException(InvalidRequestException ex){
        log.error("Petition not valid: {}", ex.getMessage());
        return buildResponse(HttpStatus.BAD_REQUEST, ex.getMessage());


    }

    //---
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<Map<String,Object>>handleValidationErrors(MethodArgumentNotValidException ex){
        log.error("Validation Error: {}", ex.getMessage());

        Map<String, String> validationErrors = new HashMap<>();
        ex.getBindingResult().getFieldErrors()
                        .forEach(error -> validationErrors.put(error.getField(), error.getDefaultMessage()));



        Map<String, Object> body = new HashMap<>();
        body.put("timestamp", LocalDateTime.now());
        body.put("status", HttpStatus.BAD_REQUEST.value());
        body.put("error", "validation Error");
        body.put("message", validationErrors);


        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(body);

     //   return buildResponse(HttpStatus.BAD_REQUEST, va);

    }


    @ExceptionHandler(Exception.class)
    public ResponseEntity<Map<String,Object>>handleGeneralException(Exception ex){
        log.error("Unexpected Error: ", ex);
        return buildResponse(HttpStatus.INTERNAL_SERVER_ERROR, "An internal error ocurred, please contact support");
    }






    public ResponseEntity<Map<String,Object>>buildResponse(HttpStatus status, String message){

        Map<String, Object> body = new HashMap<>();
        body.put("timestamp", LocalDateTime.now());
        body.put("status", status.value());
        body.put("error", status.getReasonPhrase());
        body.put("message", message);
        return ResponseEntity.status(status).body(body);


    }



}


 */
